### ISSUE TITLE
OMG why no kugo !!!! Please!!!

### ISSUE THREAD

**Issue by qinyj12** [choose-a/proprietary_vendor_sony#1]
Sorry for disturbing.
Can you add kugo's vendor? 
Cause I am not able to extract the vendor.
Thanks a lot.
GOD bless u.

**Comment by humberos** [comment]
nope, sorry!
all vendor files are now released from Sony Open Devices project:
https://developer.sony.com/develop/open-devices/downloads/software-binaries

If you check the last commit I am removing loire, tone and yoshino platforms.
